FROM centos:latest

# Reconfigure yum mirrors
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*


# Install SSH server
RUN yum install -y openssh-server python3 && \
    yum clean all

# Modify ssh config
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
RUN sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config
RUN sed -i 's/^#AuthorizedKeysFile/AuthorizedKeysFile/' /etc/ssh/sshd_config

# Generate SSH host keys
RUN ssh-keygen -A

# Add authorized_keys file
COPY authorized_keys /root/.ssh/authorized_keys


EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]