---
# Installation steps for playbooks/roles/apache-role
- name: 'Rkhunter | Install Debian packages'
  when: ansible_os_family == 'Debian'
  become: true
  apt:
    name: '{{ item.name if item.version is not defined else item.name + "=" + item.version }}'
    state: '{{ item.state | default(omit) }}'
  loop: '{{ rkhunter_packages }}'

- name: 'Rkhunter | Install RedHat packages'
  when: ansible_os_family == 'RedHat'
  become: true
  dnf:
    name: '{{ item.name if item.version is not defined else item.name + "=" + item.version }}'
    state: '{{ item.state | default(omit) }}'
  loop: '{{ rkhunter_packages }}'

- name: 'Rkhunter | Install Archlinux package'
  when: ansible_os_family == 'Archlinux'
  become: true
  community.general.pacman:
    name: '{{ item.name if item.version is not defined else item.name + "=" + item.version }}'
    state: '{{ item.state | default(omit) }}'
  loop: '{{ rkhunter_packages }}'

- name: 'Rkhunter | Install Alpine package'
  when: ansible_os_family == 'Alpine'
  become: true
  community.general.apk:
    name: '{{ item.name if item.version is not defined else item.name + "=" + item.version }}'
    state: '{{ item.state | default(omit) }}'
    upgrade: '{{ item.upgrade | default(omit) }}'
    no_cache: True # Alpine on docker seems to require this
  loop: '{{ rkhunter_packages }}'

- name: 'Rkhunter | Install Suse package'
  when: ansible_os_family == 'Suse'
  become: true
  community.general.zypper:
    name: '{{ item.name if item.version is not defined else item.name + "=" + item.version }}'
    state: '{{ item.state | default(omit) }}'
  loop: '{{ rkhunter_packages }}'
