---
# tasks file for playbooks/roles/rkhunter-role

- name: 'Rkhunter | Include OS-specific variables.'
  include_vars: '{{ ansible_os_family }}.yml'

- name: 'Rkhunter | Define packages'
  set_fact:
    rkhunter_packages: '{{ rkhunter_default_packages }}'
  when: 'not rkhunter_packages'

- import_tasks: 'install.yml'

- import_tasks: 'configure.yml'
