---
- name: 'Update Debian packages'
  when: ansible_os_family == 'Debian'
  become: true
  apt:
    name: "*"
    state: latest
    update_cache: yes
  async: 3600
  poll: 0
  register: _debian_upgrade

- name: 'Update RedHat packages'
  when: ansible_os_family == 'RedHat'
  become: true
  dnf:
    name: '*'
    state: latest
  async: 3600
  poll: 0
  register: _rhel_upgrade

- name: 'Update Archlinux packages'
  when: ansible_os_family == 'Archlinux'
  become: true
  community.general.pacman:
    update_cache: true
    upgrade: true
  async: 3600
  poll: 0
  register: _arch_upgrade
    
- name: 'Update Suse packages'
  when: ansible_os_family == 'Suse'
  become: true
  community.general.zypper:
    name: '*'
    state: latest
  async: 3600
  poll: 0
  register: _suse_upgrade

- name: 'Update Alpine packages'
  when: ansible_os_family == 'Alpine'
  become: true
  community.general.apk:
    update_cache: true
    upgrade: true
  async: 3600
  poll: 0
  register: _alpine_upgrade

- name: 'Check async jobs status'
  async_status:
    jid: "{{ item.ansible_job_id }}"
  loop:
    - "{{ _alpine_upgrade }}"
    - "{{ _arch_upgrade }}"
    - "{{ _rhel_upgrade }}"
    - "{{ _suse_upgrade }}"
    - "{{ _debian_upgrade }}"
  register: job_result
  until: job_result.finished
  retries: 2
  delay: 1800
  when: item.ansible_job_id is defined

- name: Check RHEL Upgrade status
  debug:
    msg: "{{ _rhel_upgrade }}"