---
- name: 'Update Debian packages'
  when: ansible_os_family == 'Debian'
  become: true
  apt:
    name: "*"
    state: latest
    update_cache: yes


- name: 'Update RedHat packages'
  when: ansible_os_family == 'RedHat'
  become: true
  dnf:
    name: '*'
    state: latest


- name: 'Update Archlinux packages'
  when: ansible_os_family == 'Archlinux'
  become: true
  community.general.pacman:
    update_cache: true
    upgrade: true

    
- name: 'Update Suse packages'
  when: ansible_os_family == 'Suse'
  become: true
  community.general.zypper:
    name: '*'
    state: latest


- name: 'Update Alpine packages'
  when: ansible_os_family == 'Alpine'
  become: true
  community.general.apk:
    update_cache: true
    upgrade: true
