---
- name: Update DEBIAN packages
  when: ansible_os_family == 'Debian' and ansible_user == 'me'
  become: true
  apt:
    name: "*"
    state: latest
    update_cache: yes
  async: 3600
  poll: 0
  register: _debian_upgrade

- name: 'Update RedHat packages'
  when: ansible_os_family == 'RedHat' and ansible_user == 'me'
  become: true
  dnf:
    name: '*'
    state: latest
  async: 3600
  poll: 0
  register: _rhel_upgrade

- name: Update ARCH packages
  when: ansible_os_family == 'Archlinux' and ansible_user == 'me'
  become: true
  community.general.pacman:
    update_cache: true
    upgrade: true
  async: 3600
  poll: 0
  register: _arch_upgrade
    
- name: 'Update Suse packages'
  when: ansible_os_family == 'Suse' and ansible_user == 'me'
  become: true
  community.general.zypper:
    name: '*'
    state: latest
  async: 3600
  poll: 0
  register: _suse_upgrade

- name: 'Update Alpine packages'
  when: ansible_os_family == 'Alpine'
  become: true
  community.general.apk:
    update_cache: true
    upgrade: true
  async: 3600
  poll: 0
  register: _alpine_upgrade

- async_status:
    jid: "{{ item.ansible_job_id }}"
  loop:
    - "{{ _alpine_upgrade }}"
  register: job_result
  until: job_result.finished
  retries: 30
  delay: 30