---

- name: 'NTP | Configure NTP timezone file.'
  become: yes
  file:
    src: '/usr/share/zoneinfo/{{ ntp_timezone }}'
    dest: '/etc/localtime'
    state: 'link'
    force: yes
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'NTP | Service restart'

- name: 'NTP | Configure NTP conf file.'
  become: yes
  template:
    src: '{{ ntp_conf_template }}'
    dest: '/etc/ntp.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'NTP | Service restart'