---
# defaults file for ntp-role
ntp_timezone: 'UTC'
ntp_packages:
ntp_service_name:
ntp_service_state: 'started'
ntp_service_enabled: yes
ntp_conf_template: 'ntp.j2'
ntp_drift_file: '/var/lib/ntp/ntp.drift'
ntp_statistics_dir:
ntp_statistics: 'loopstats peerstats clockstats'
ntp_file_generation_sets:
  - 'filegen loopstats file loopstats type day enable'
  - 'filegen peerstats file peerstats type day enable'
  - 'filegen clockstats file clockstats type day enable'
ntp_servers:
  - '0.pool.ntp.org'
  - '1.pool.ntp.org'
  - '2.pool.ntp.org'
  - '3.pool.ntp.org'
ntp_restrictions:
  - 'restrict -4 default kod notrap nomodify nopeer noquery'
  - 'restrict -6 default kod notrap nomodify nopeer noquery'
  - 'restrict 127.0.0.1'
  - 'restrict ::1'