---
# tasks file for playbooks/roles/apache-role

- name: 'Apache | Include OS-specific variables.'
  include_vars: '{{ ansible_os_family }}.yml'

- name: 'Apache | Define service name'
  set_fact:
    apache_service_name: '{{ apache_default_service_name }}'
  when: 'not apache_service_name'

- name: 'Apache | Define packages'
  set_fact:
    apache_packages: '{{ apache_default_packages }}'
  when: 'not apache_packages'

- name: 'Apache | Define user'
  set_fact:
    apache_user: '{{ apache_default_user }}'
  when: 'not apache_user'
    

- import_tasks: 'install.yml'

- import_tasks: 'configure.yml'

- import_tasks: 'service.yml'
    