- name: Debug Distribution
  hosts: vms
  gather_facts: true
  become: true

  tasks:
    - name: Display guest info
      debug:
        msg: "Family/Distribuition: {{ ansible_os_family }}/{{ ansible_distribution }} | Remote user: {{ machine_user }}"
    
    - name: Whoami user
      become_user: "{{ machine_user }}"
      command: whoami
      register: whoami_user
      changed_when: false

    - name: Whoami root
      command: whoami
      register: whoami_root
      changed_when: false

    - name: Display users
      debug:
        msg: "whoami_user: {{ whoami_user.stdout }}, whoami_root: {{ whoami_root.stdout }}"

    - name: Get user crons
      become_user: "{{ machine_user }}"
      command: crontab -l
      register: existing_crons
      changed_when: false
      ignore_errors: true

    - name: Display Cronjobs
      debug:
        var: existing_crons
      when: existing_crons is succeeded
    
    - name: Get root crons
      command: crontab -l
      register: existing_root_crons
      changed_when: false
      ignore_errors: true

    - name: Does not have rkhunter update
      debug:
        msg: Does not have rkhunter update cronjob
      when: (existing_root_crons is succeeded and not existing_root_crons.stdout_lines is search("rkhunter --cronjob --update --quiet")) or existing_root_crons.stderr is search("no crontab for root")

    - name: Has clamdscan
      debug:
        msg: Has clamdscan
      when: existing_crons is succeeded and existing_crons.stdout_lines is search("clamdscan")
